# generated by theme-apply - edit general.conf.tpl instead
# See https://wiki.hyprland.org/Configuring/Variables/ for more
general {
    gaps_in = 4
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(${ACCENT}ee) rgba(${ACTIVE}ee) 45deg
    col.inactive_border = rgba(${INACTIVE}aa)
    layout = dwindle
    resize_on_border = true
}
