/* generated by theme-apply - edit theme.rasi.tpl instead */

* {
    background:     #${BG}FF;
    background-alt: #${BG_ALT}FF;
    foreground:     #${FG}FF;
    selected:       #${ACCENT}FF;
    active:         #${ACTIVE}FF;
    urgent:         #${URGENT}FF;
}
